version: '3.7'

services:
  mongod:
    image: mongo
    ports:
      - 27017:27017
  mongo_seed:
    image: mongo
    links:
      - mongod
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
  indexer:
    build: "./indexer"
    depends_on:
      - mongod
    ports:
      - 8081:8081
    environment:
      - MONGO_URI=mongodb://mongod:27017
      - CHAT_DB=search
    volumes:
      - index-volume:/indexedFiles
  searcher:
    build: "./searcher"
    depends_on:
      - indexer
    ports:
      - 8082:8082
    volumes:
      - index-volume:/indexedFiles

volumes:
  index-volume:
